In [1]:
# Importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# y la distribución de las variables
# ------------------------------------------------------------------------------
import scipy.stats as stats

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames
#pd.set_option('display.max_rows', None)
# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("world-happiness-report-2021.csv")
df

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [3]:
# Lista de nombres de columnas a eliminar
columnas_a_eliminar = ["upperwhisker", "lowerwhisker","Explained by: Log GDP per capita", "Explained by: Social support", 
                       "Explained by: Healthy life expectancy", "Explained by: Freedom to make life choices","Explained by: Generosity",
                       "Explained by: Perceptions of corruption","Dystopia + residual"]

# Eliminar las columnas utilizando el método .drop()
df = df.drop(columnas_a_eliminar, axis=1)

# axis=1 indica que estamos eliminando columnas (axis=0 sería para filas)

# Si deseas hacer cambios en el DataFrame original, puedes usar el argumento inplace=True
# df.drop(columnas_a_eliminar, axis=1, inplace=True)

In [4]:
df

,Country name,Regional indicator,Ladder score,Standard error of ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia
0,Finland,Western Europe,7.842,0.032,10.775,0.954,72.000,0.949,-0.098,0.186,2.43
1,Denmark,Western Europe,7.620,0.035,10.933,0.954,72.700,0.946,0.030,0.179,2.43
2,Switzerland,Western Europe,7.571,0.036,11.117,0.942,74.400,0.919,0.025,0.292,2.43
3,Iceland,Western Europe,7.554,0.059,10.878,0.983,73.000,0.955,0.160,0.673,2.43
4,Netherlands,Western Europe,7.464,0.027,10.932,0.942,72.400,0.913,0.175,0.338,2.43
...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,7.926,0.787,48.700,0.715,-0.131,0.915,2.43
145,Botswana,Sub-Saharan Africa,3.467,0.074,9.782,0.784,59.269,0.824,-0.246,0.801,2.43
146,Rwanda,Sub-Saharan Africa,3.415,0.068,7.676,0.552,61.400,0.897,0.061,0.167,2.43
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,7.943,0.750,56.201,0.677,-0.047,0.821,2.43
148,Afghanistan,South Asia,2.523,0.038,7.695,0.463,52.493,0.382,-0.102,0.924,2.43

In [5]:
# Crear un diccionario con los nuevos nombres de las columnas
nuevos_nombres = {"Country name":"Country"}

# Cambiar los nombres de las columnas utilizando el método .rename()
df = df.rename(columns=nuevos_nombres)

In [6]:
df

,Country,Regional indicator,Ladder score,Standard error of ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia
0,Finland,Western Europe,7.842,0.032,10.775,0.954,72.000,0.949,-0.098,0.186,2.43
1,Denmark,Western Europe,7.620,0.035,10.933,0.954,72.700,0.946,0.030,0.179,2.43
2,Switzerland,Western Europe,7.571,0.036,11.117,0.942,74.400,0.919,0.025,0.292,2.43
3,Iceland,Western Europe,7.554,0.059,10.878,0.983,73.000,0.955,0.160,0.673,2.43
4,Netherlands,Western Europe,7.464,0.027,10.932,0.942,72.400,0.913,0.175,0.338,2.43
...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,7.926,0.787,48.700,0.715,-0.131,0.915,2.43
145,Botswana,Sub-Saharan Africa,3.467,0.074,9.782,0.784,59.269,0.824,-0.246,0.801,2.43
146,Rwanda,Sub-Saharan Africa,3.415,0.068,7.676,0.552,61.400,0.897,0.061,0.167,2.43
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,7.943,0.750,56.201,0.677,-0.047,0.821,2.43
148,Afghanistan,South Asia,2.523,0.038,7.695,0.463,52.493,0.382,-0.102,0.924,2.43

In [8]:
def data_exploring(csv):
    forma = csv.shape
    print(f"La forma es {forma}")
    print("_______________")
    columnas = csv.columns
    print(f"Las columnas son {columnas}")
    print("_______________")
    nulos = csv.isna().sum().reset_index()
    print(f"Los nulos son:")
    display(nulos)
    print("_______________")
    duplicados = csv.duplicated().sum()
    print(f"Hay {duplicados} duplicados")
    print("_______________")
    tipo_dato = csv.dtypes.reset_index()
    print(f"Los datos son de tipo:")
    display(tipo_dato)

In [9]:
data_exploring(df)

La forma es (149, 11)
_______________
Las columnas son Index(['Country', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia'],
      dtype='object')
_______________
Los nulos son:

                             index  0
0                          Country  0
1               Regional indicator  0
2                     Ladder score  0
3   Standard error of ladder score  0
4            Logged GDP per capita  0
5                   Social support  0
6          Healthy life expectancy  0
7     Freedom to make life choices  0
8                       Generosity  0
9        Perceptions of corruption  0
10        Ladder score in Dystopia  0

_______________
Hay 0 duplicados
_______________
Los datos son de tipo:

                             index        0
0                          Country   object
1               Regional indicator   object
2                     Ladder score  float64
3   Standard error of ladder score  float64
4            Logged GDP per capita  float64
5                   Social support  float64
6          Healthy life expectancy  float64
7     Freedom to make life choices  float64
8                       Generosity  float64
9        Perceptions of corruption  float64
10        Ladder score in Dystopia  float64

In [10]:
df.to_csv("happiness_clean.csv")